### ISSUE TITLE
undefined method `loadInitialValues` for VersiononeSdk::Asset

### ISSUE THREAD

**Issue by pccasto** [grokify/versionone-sdk-ruby#1]
Initializer for `asset.rb` has this:

``` ruby
self.loadInitialValues(dValues)
```

Initializer for `JsonDoc::Document` has this:

``` ruby
self.loadHash(dValues) if dValues.is_a?(Hash)
```

Couldn't find any place where `loadInitialValues` was defined, so Monkeypatched the Asset class to use the same logic as `JsonDoc::Document`.  That got me past the error.  Not sure if that is the optimal approach, but got it working.

It looks like it might be cleaner for `VersiononeSdk::Asset.initialize` to call `super`? 

Just starting to experiment with this module, and VersionOne API, but thought I'd raise this for review.

Oh - and editing this to include a Thank You for creating this in the first place :-) !

**Comment by grokify** [comment]
Thanks for pointing this out. I've pushed version `0.1.2` which should fix this issue. Please try it out.

**Comment by pccasto** [comment]
Thanks very much for updating.  I've installed the updated gem (which also pulled the updated JsonDoc gem).  Was able to run the code without my previous patch.  So all is well.

I have some other ideas for this gem, feature wise ...  My use case is fairly narrow (synchronizing some bits of VersionOne with JIRA for our particular workflows).  Not sure the shape that effort is going to take yet.  I'll try to fork and provide pull requests once I explore the API a bit more.

**Comment by grokify** [comment]
Glad to hear the update is working for you.

Your use case sounds like it could be useful. I used VersionOne and JIRA on the same project and it would have been useful to have an auto-synchronization capability. If you end up building, it feel free to send a pull request.
